
export const projects = [
    { name: "Davtion Dev ", description: "Proyecto de tareas complejo donde se utiliza apollo client para testear en paralelo el local state management y llamadas a la api creada desde cero con apollo server express. ", technologies: ["React", "Apollo Client", "Graphql", "Postcss", "TypeScript"], image: "/davtion2.png", link: "https://davtion.netlify.app" },
    { name: "Art Gallery", description: "Aplicación para poder ver fotos en alta calidad e interactuar con ellas. Utilizo la API de Unsplash para poder darle vida  al página web", technologies: ["React", "TypeScript", "Axios", "Css Modules"], image: "https://res.cloudinary.com/dedkiuenu/image/upload/v1650831361/portfolio--web/artG_y9mgrd.png", link: "https://bright-buttercream-6df396.netlify.app/", "code": "https://github.com/itsDavidev/artGallery" },
    { name: "Blog", description: "Blog creado con para poder compartir con otros usuarios y con la comunidad de desarrolladores de la web, como poder llegar solucionar algunos errores que se presentan en la web.", technologies: ["Strapi", "React", "Graphql", "Apollo Server", "Styeled Componets"], image: "https://res.cloudinary.com/dedkiuenu/image/upload/v1650831364/portfolio--web/blog_mbrmxt.png", link: "https://dblogv1strapi.netlify.app", "code": "https://github.com/itsDavidev/Dblogv1" },
    { name: "DavWord", description: "Es una aplicación web inspirada en el juego WORDLE, que se hizo muy popular durante una época en donde pongo en práctica los conceptos sobre Web Components con todo el potencial y facilidad que pueden ofrecer.", technologies: ["Web Components", "JavaScript", "css", "vite", "HTML"], image: "https://res.cloudinary.com/dedkiuenu/image/upload/v1650831372/portfolio--web/davword_fssti3.png", link: "", "code": "https://github.com/itsDavidev/DavWordle" },
    { name: "Login Web3", description: "Login que utiliza web 3 para poder interactuar con  Ethereum, atreves de un wallet de metamask. En ella pongo en práctica el manejo las diferentes funciones de la blockchain.", technologies: ["Ethers", "React", "styled components", "TypeScript"], image: "https://res.cloudinary.com/dedkiuenu/image/upload/v1650831352/portfolio--web/login_thlzyl.png", link: "https://loginweb3.netlify.app", "code": "https://github.com/itsDavidev/web3Login" },
    { name: "Landing Page NFT", description: "Maquetacion de un landing page sobre nfts en donde pongo en practica el uso de Web Components", technologies: ["WebComponents", "HTML", "Css", "JavaScript", "vite"], image: "https://res.cloudinary.com/dedkiuenu/image/upload/v1650831345/portfolio--web/ladingpagenft_r3ttsh.png", link: "", "code": "https://github.com/itsDavidev/LadingPage-NFT" },
    { name: "Creative Web Personal", description: "Maquetacion de un portfolio web creado desde cero con tecnologias web.", technologies: ["Astro", "Lit", "JavaScript", "Css"], image: "/creative.jpg", link: "https://creative-personal-website.vercel.app/", code: "https://github.com/itsDavidev/creative_personal_website" },
    { name: "Ultra NFT", description: "Maquetacion sobre ", technologies: ["Astro", "Lit", "JavaScript", "Css"], image: "/ultranft.jpg", link: "https://ultra-nft.vercel.app/", code: "https://github.com/itsDavidev/ultraNFT" },
    { name: "Git Search", description: "Buscador de usuarios de github que ocupa la API de Github.", technologies: ["Web Components", "JavaScript", "Css", "Axios"], image: "/gitsearch.jpg", link: "https://git-search-rho.vercel.app/", code: "https://github.com/itsDavidev/gitSearch" },
    { name: "Ecoomerce Frotend ", description: "Maquetacion de un reto de Frotend Mentor donde se muestra la pagina para comprar un producto", technologies: ["React", "Tailwind Css",], image: "/Ecoomerce.jpg", link: "https://ecomercefrontend.vercel.app/", code: "https://github.com/itsDavidev/ecomercefrontend" },
    { name: "Agency Page", description: "Reto de Frontend Mentor donde pongo prueba mis habilidades donde apartir de un diseño de una pagina web, puedo maquetar el diseño", technologies: ["Postcss", "HTML", "Vite"], image: "/AgencyPage.jpg", link: "https://agencypagelanding.vercel.app/", code: " https://github.com/itsDavidev/agencyPage" },
    {
        name: "DavCovid", description: "davcovid aplicacion para conocer el estado del covid en los paises. Donde practico consultas a una API. ", technologies: ["React", "JavaScript", "Sass", "Css", "Axios"], image: "/public/davcovid.jpg", link: "https://david-prueba-covid.netlify.app/", code: "https://github.com/itsDavidev/CovidDav"
    }
]
